Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2021-11, with the labels that each got.

#315 Adding missing DLLogger requirement for the paper reproducibility example
  examples/t4rec_paper_experiments/requirements.txt
Labels: status/needs-review, size/XS

#311 Disable stochastic swap noise during eval
  tests/tf/tabular/test_transformations.py
  tests/torch/tabular/test_transformations.py
  transformers4rec/config/transformer.py
  transformers4rec/torch/tabular/transformations.py
Labels: status/needs-review

#334 Quick fix of the value returned by fit_and_evaluate
  examples/end-to-end-session-based/end-to-end-session-based-with-Yoochoose.ipynb
  transformers4rec/torch/utils/examples_utils.py
Labels: area/pytorch, size/XS

#332 Getting-started notebook with CLM task
  examples/getting-started-session-based/03-session-based-XLNet-with-TF.ipynb
  tests/tf/test_ranking_metrics.py
  transformers4rec/tf/ranking_metric.py
Labels: area/tensorflow
