Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2021-09, with the labels that each got.

#228 Adding PR- and Issue-templates
  .github/ISSUE_TEMPLATE/--new-model-addition.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/submit-question.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: status/needs-review

#240 Adding status batches to README
  README.md
Labels: area/documentation, status/needs-review, size/XS

#245 Add LabelSmoothCrossEntropyLoss util class
  tests/torch/test_losses.py
  transformers4rec/torch/losses.py
Labels: P0, area/pytorch, paper reproducibility, status/needs-review

#244 Check for the correct pairs of (transformers, masking scheme)
  docs/source/resources.md
  tests/torch/block/test_transformer.py
  transformers4rec/config/transformer.py
  transformers4rec/torch/block/transformer.py
  transformers4rec/torch/utils/torch_utils.py
Labels: P0, area/pytorch, status/needs-review

#248 Change dataloader func and add barcharts for results
  examples/tutorial/03-Session-based-recsys.ipynb
  examples/tutorial/visuals.py
Labels: area/tutorial, status/needs-review

#256 Updating paper references in the documentation
  README.md
  docs/source/model_definition.md
  docs/source/resources.md
  docs/source/why_transformers4rec.md
Labels: status/needs-review
