Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2022-12, with the labels that each got.

#520 docs: Add semver to calver banner
  docs/source/_static/css/custom.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation

#518 docs: Add basic SEO configuration
  docs/Makefile
  docs/source/conf.py
Labels: documentation

#552 Serving tfrec with pyt backend example
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
  examples/getting-started-session-based/schema.pb
Labels: area/inference, examples

#546 Refactor part2
  examples/tutorial/03-Session-based-recsys.ipynb
  tests/torch/model/test_head.py
  tests/torch/model/test_model.py
  tests/torch/test_losses.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
  transformers4rec/torch/utils/torch_utils.py
Labels: enhancement, area/api

#562 Address review feedback
  README.md
Labels: documentation

#571 Fix the test data path in Trainer.predict()
  transformers4rec/torch/trainer.py
Labels: bug

#574 Update mypy version from 0.971 to 0.991
  .pre-commit-config.yaml
Labels: ci

#576 Fix error raised by latest Torchmetrics (0.11.0)
  requirements/pytorch.txt
  tests/torch/test_trainer.py
  transformers4rec/torch/model/prediction_task.py
Labels: bug

#572 Support to pre-trained embeddings initializer (trainable or not)
  tests/torch/features/test_embedding.py
  transformers4rec/torch/__init__.py
  transformers4rec/torch/features/embedding.py
Labels: enhancement

#580 Change data_loader_engine to 'merlin' in examples
  ci/test_integration.sh
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/t4rec_paper_experiments/README.md
  examples/tutorial/03-Session-based-recsys.ipynb
Labels: area/examples, chore, ci

#428 Transformers4Rec Docs Restructure
  .github/workflows/ci.yml
  .github/workflows/docs-sched-rebuild.yaml
  README.md
  docs/source/model_definition.md
  docs/source/pipeline.md
  docs/source/resources.md
  docs/source/training_eval.md
  docs/source/why_transformers4rec.md
  tox.ini
Labels: documentation

#585 adding workflow for gpu ci on gha runner
  .github/workflows/gpu-ci.yml
Labels: chore, ci

#587 Install systems for testing notebooks
  requirements/systems.txt
  requirements/test.txt
  tox.ini
Labels: area/tests, chore

#588 Revert "Install systems for testing notebooks (#587)"
  requirements/systems.txt
  requirements/test.txt
  tox.ini
Labels: chore
