Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2022-09, with the labels that each got.

#482 Update nv logo in the notebooks
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/tutorial/01-preprocess.ipynb
  examples/tutorial/02-ETL-with-NVTabular.ipynb
  examples/tutorial/03-Session-based-recsys.ipynb
  examples/tutorial/04-Inference-with-Triton.ipynb
Labels: enhancement, examples

#483 [BUG] trainer.model.module renamed and DataParallel mode fixed
  transformers4rec/torch/trainer.py
Labels: bug

#486 Adjust the device used in synthetic data generation
  .pre-commit-config.yaml
  tests/data/testing/test_dataset.py
  transformers4rec/data/dataset.py
  transformers4rec/torch/utils/schema_utils.py
Labels: area/pytorch, chore
