Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2022-11, with the labels that each got.

#507 Add save/load & input/output schema methods to T4Rec Model class
  tests/torch/model/test_model.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
Labels: enhancement

#522 Fix name and bug in MeanReciprocalRankAt
  tests/torch/test_ranking_metrics.py
  transformers4rec/torch/ranking_metric.py
Labels: chore

#521 Add multi-gpu training example for T4Rec PyTorch
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
Labels: examples

#523 Specify output dtype for Normalize op in ETL example to match model expectations
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/tutorial/02-ETL-with-NVTabular.ipynb
Labels: chore

#527 run github action tests and lint via tox, with upstream deps installed
  .github/workflows/ci.yml
  requirements/dev.txt
  requirements/docs.txt
  requirements/test.txt
  tox.ini
Labels: chore, ci

#532 Do not commit unnecessary doc files
  .github/workflows/docs-sched-rebuild.yaml
  docs/source/conf.py
Labels: chore, skip-changelog

#531 Remove stale documentation reviews
  .github/workflows/docs-remove-stale-reviews.yaml
Labels: chore

#533 Add docs requirements to extras list in setup.py
  requirements/docs.txt
  setup.py
Labels: documentation, ci

#535 Update actions for docs builds
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/docs-sched-rebuild.yaml
Labels: chore, skip-changelog

#536 Fix CI test based on the requirements of the new merlin loader
  ci/test_integration.sh
  transformers4rec/torch/losses.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/torch/utils/torch_utils.py
Labels: bug, P0, ci

#539 Fix dtype mismatch in CLM masking class due to new data loader changes
  transformers4rec/torch/masking.py
Labels: bug

#541 Fix failing ci error related to `sparse_names` containing features that are not part of the model's schema
  transformers4rec/torch/utils/data_utils.py
Labels: bug, ci

#529 Specify packages to look for in setup.py to avoid publishing tests
  MANIFEST.in
  setup.py
Labels: chore

#545 Add lint workflow to run pre-commit on all files
  .github/workflows/blossom-ci.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  merlin_standard_lib/schema/schema.py
  mypy.ini
  pyproject.toml
  requirements/dev.txt
  setup.cfg
  tests/data/test_preprocessing.py
  tests/unit/test_notebooks.py
  tox.ini
Labels: ci

#543 Refactoring part1- flags modification
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py
  examples/tutorial/03-Session-based-recsys.ipynb
  tests/torch/conftest.py
  tests/torch/features/test_sequential.py
  tests/torch/model/test_head.py
  tests/torch/model/test_model.py
  tests/torch/test_losses.py
  tests/torch/test_torchscript.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/experimental.py
  transformers4rec/torch/features/sequence.py
  transformers4rec/torch/masking.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
Labels: enhancement, area/api

#548 Minor updates to notebook texts
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
Labels: examples

#540 Add music-streaming synthetic data to test the support of all predictions tasks with the Trainer class
  tests/torch/test_trainer.py
  transformers4rec/data/__init__.py
  transformers4rec/data/testing/music_streaming/data.parquet
  transformers4rec/data/testing/music_streaming/dataset.py
  transformers4rec/data/testing/music_streaming/schema.json
Labels: enhancement, Multi-GPU, area/tests

#547 Uses merlin-dataloader package
  merlin_standard_lib/utils/misc_utils.py
  requirements/dataloader.txt
  setup.py
  tox.ini
  transformers4rec/config/trainer.py
  transformers4rec/data/preprocessing.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/utils/dependencies.py
Labels: chore

#551 Fix discrepancy between evaluation and inference modes
  ci/test_integration.sh
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py
  examples/tutorial/03-Session-based-recsys.ipynb
  tests/torch/features/test_sequential.py
  tests/torch/test_masking.py
  transformers4rec/config/transformer.py
  transformers4rec/torch/features/sequence.py
  transformers4rec/torch/masking.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
  transformers4rec/torch/utils/data_utils.py
Labels: bug, area/inference
