Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2022-10, with the labels that each got.

#496 [feature]Multi-GPU DistributedDataParallel Fixed
  transformers4rec/torch/ranking_metric.py
  transformers4rec/torch/trainer.py
  transformers4rec/torch/utils/data_utils.py
Labels: enhancement, status/needs-review

#498 Set `ignore_masking` to True by default
  tests/torch/model/test_head.py
  tests/torch/test_losses.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/experimental.py
  transformers4rec/torch/features/sequence.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
Labels: enhancement, area/inference

#503 Multi-GPU training with DP and DDP documentation
  _images/DP_DDP_perf.png
  docs/source/multi_gpu_train.md
  docs/source/toc.yaml
Labels: documentation, status/needs-review
