Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2022-07, with the labels that each got.

#434 support sequential binary task
  tests/torch/model/test_head.py
  transformers4rec/torch/model/base.py
Labels: enhancement, P1, area/pytorch, status/needs-review, size/XS

#450 Update requirement on `nvidia-dllogger` to follow install instructions
  examples/t4rec_paper_experiments/requirements.txt
Labels: area/tests, chore

#448 Move Tensorflow code to `tensorflow` branch
  ci/test_unit.sh
  tests/conftest.py
  tests/tf/__init__.py
  tests/tf/block/__init__.py
  tests/tf/block/test_base.py
  tests/tf/block/test_dlrm.py
  tests/tf/block/test_mlp.py
  tests/tf/block/test_transformer.py
  tests/tf/conftest.py
  tests/tf/features/__init__.py
  tests/tf/features/test_continuous.py
  tests/tf/features/test_embedding.py
  tests/tf/features/test_sequence.py
  tests/tf/features/test_tabular.py
  tests/tf/model/__init__.py
  tests/tf/model/test_head.py
  tests/tf/model/test_model.py
  tests/tf/tabular/__init__.py
  tests/tf/tabular/test_aggregation.py
  tests/tf/tabular/test_tabular.py
  tests/tf/tabular/test_transformations.py
  tests/tf/test_masking.py
  tests/tf/test_public_api.py
  tests/tf/test_ranking_metrics.py
  tests/tf/utils/__init__.py
  tests/tf/utils/test_schema_utils.py
  transformers4rec/tf/__init__.py
  transformers4rec/tf/block/__init__.py
  transformers4rec/tf/block/base.py
  transformers4rec/tf/block/dlrm.py
  transformers4rec/tf/block/mlp.py
  transformers4rec/tf/block/transformer.py
  transformers4rec/tf/features/__init__.py
  transformers4rec/tf/features/base.py
  transformers4rec/tf/features/continuous.py
  transformers4rec/tf/features/embedding.py
  transformers4rec/tf/features/sequence.py
  transformers4rec/tf/features/tabular.py
  transformers4rec/tf/features/text.py
  transformers4rec/tf/layers/__init__.py
  transformers4rec/tf/layers/interaction.py
  transformers4rec/tf/layers/outer_product.py
  transformers4rec/tf/masking.py
  transformers4rec/tf/model/__init__.py
  transformers4rec/tf/model/base.py
  transformers4rec/tf/model/prediction_task.py
  transformers4rec/tf/ranking_metric.py
  transformers4rec/tf/tabular/__init__.py
  transformers4rec/tf/tabular/aggregation.py
  transformers4rec/tf/tabular/base.py
  transformers4rec/tf/tabular/transformations.py
  transformers4rec/tf/typing.py
  transformers4rec/tf/utils/__init__.py
  transformers4rec/tf/utils/repr_utils.py
  transformers4rec/tf/utils/schema_utils.py
  transformers4rec/tf/utils/testing_utils.py
  transformers4rec/tf/utils/tf_utils.py
Labels: area/tensorflow, chore

#445 Update the conda install command
  README.md
Labels: documentation

#444 Add PostContextFusion block to support Latent Cross technique
  tests/torch/test_experimental.py
  transformers4rec/torch/experimental.py
Labels: enhancement, P1, area/pytorch, status/needs-review, size/S

#436 Add the support of prediction step to the Trainer class
  tests/torch/features/test_sequential.py
  tests/torch/test_trainer.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/features/sequence.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
Labels: enhancement, P0, area/pytorch, status/needs-review, size/S

#455 Don't git pull origin main in unit and integration tests, use container version
  ci/test_integration.sh
  ci/test_unit.sh
Labels: chore

#454 Change the metric names prefix to align with the HF trainer code.
  tests/torch/test_trainer.py
  transformers4rec/torch/trainer.py
Labels: bug, area/transformers, area/pytorch, size/XS

#458 Remove unnecessary docs dependencies
  docs/source/conf.py
  requirements/dev.txt
Labels: chore

#462 Small fixes in the example notebooks
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/end-to-end-session-based/03-End-to-end-session-based-with-Yoochoose-TF.ipynb
Labels: enhancement, area/examples
