Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-02, with the labels that each got.

#608 Update branch name extraction for tag builds
  .github/workflows/ci.yml
  .github/workflows/gpu-ci.yml
Labels: ci

#609 Fetch release branches so that we can figure out the release branch
  .github/workflows/ci.yml
  .github/workflows/gpu-ci.yml
Labels: ci

#617 Bump the versions of precommit hook packages
  .pre-commit-config.yaml
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_args.py
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py
  examples/tutorial/visuals.py
  tests/torch/block/test_transformer.py
  tests/torch/tabular/test_transformations.py
  tests/torch/test_experimental.py
  tests/torch/test_torchscript.py
  tests/torch/test_trainer.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/trainer.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/torch/utils/torch_utils.py
Labels: chore

#616 docs: Rebuild on push to the default branch
  .github/workflows/docs-sched-rebuild.yaml
Labels: chore, skip-changelog

#619 Start depending on Merlin models
  .github/workflows/ci.yml
  .gitignore
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/tutorial/02-ETL-with-NVTabular.ipynb
  requirements/base.txt
  requirements/base_external.txt
  requirements/base_merlin.txt
  requirements/dataloader.txt
  setup.py
  tests/conftest.py
  tests/data/test_preprocessing.py
  tests/utils/test_data_utils.py
  tox.ini
  transformers4rec/data/yoochoose.py
  transformers4rec/utils/data_utils.py
Labels: chore

#622 Move to misc_utils from merlin-models
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  merlin_standard_lib/utils/misc_utils.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/torch/utils/schema_utils.py
Labels: chore

#624 Move to Registry from merlin-models
  merlin_standard_lib/__init__.py
  merlin_standard_lib/registry.py
  transformers4rec/config/transformer.py
  transformers4rec/torch/masking.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/ranking_metric.py
  transformers4rec/torch/tabular/base.py
  transformers4rec/torch/utils/data_utils.py
Labels: chore

#621 move categorical_cardinalities out of the schema class
  merlin_standard_lib/__init__.py
  merlin_standard_lib/schema/schema.py
  merlin_standard_lib/utils/embedding_utils.py
  tests/config/test_schema.py
  tests/merlin_standard_lib/schema/test_schema.py
  transformers4rec/torch/features/embedding.py
Labels: area/api, chore
