Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-06, with the labels that each got.

#710 Build docs for stable branch and make default
  .github/workflows/docs-sched-rebuild.yaml
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/model_definition.md
  docs/source/multi_gpu_train.md
  docs/source/pipeline.md
  docs/source/resources.md
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
  examples/tutorial/02-ETL-with-NVTabular.ipynb
  examples/tutorial/03-Session-based-recsys.ipynb
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/utils/data_utils.py
Labels: documentation

#715 Add pytorch backend path to LD_LIBRARY_PATH in integration test env
  tox.ini
Labels: ci

#717 Extend LD_LIBRARY_PATH with pytorch directory
  tox.ini
Labels: ci

#706 Add missing docstrings
  transformers4rec/config/transformer.py
  transformers4rec/data/dataset.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/block/mlp.py
  transformers4rec/torch/block/transformer.py
  transformers4rec/torch/features/embedding.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/tabular/aggregation.py
  transformers4rec/torch/utils/schema_utils.py
Labels: documentation, enhancement

#649 Update minimum version of merlin-models to 23.4.0
  requirements/base_merlin.txt
Labels: status/blocked, ci

#720 Fixes on RecallAt metric for cut-off 1 and for scalar cut-off
  tests/unit/torch/test_ranking_metrics.py
  tests/unit/torch/test_trainer.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/ranking_metric.py
Labels: bug

#721 Fixed OOM issues when evaluating/predicting
  tests/unit/torch/test_trainer.py
  transformers4rec/config/trainer.py
  transformers4rec/torch/trainer.py
Labels: bug, breaking

#723 Fix the CLM performance mismatch between evaluation and manual inference
  tests/unit/torch/features/test_sequential.py
  tests/unit/torch/test_masking.py
  transformers4rec/torch/masking.py
Labels: bug

#724 Update merlin dependency versions to match 23.06 release
  requirements/base_merlin.txt
Labels: chore, skip-base-branch-check
