Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-05, with the labels that each got.

#680 update end-to-end example to use systems api
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
Labels: examples

#691 don't re-run github actions when PRs get closed
  .github/workflows/gpu-ci-integration.yml
  .github/workflows/gpu-ci.yml
Labels: ci

#695 Update tag pattern in GitHub Workflows
  .github/workflows/ci.yml
  .github/workflows/docs-sched-rebuild.yaml
  .github/workflows/gpu-ci-integration.yml
  .github/workflows/gpu-ci.yml
  .github/workflows/release-drafter.yaml
Labels: ci

#677 Remove padding from NVTabular getting started example
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
Labels: area/examples, chore

#687 Rename integration test job from `gpu-ci` to `gpu-ci-integration`
  .github/workflows/gpu-ci-integration.yml
Labels: ci

#694 Add workflows to check base branch and set stable branch
  .github/workflows/check-base-branch.yaml
  .github/workflows/set-stable-branch.yaml
Labels: ci

#688 Add Conda Package Publish Workflow
  .github/workflows/ci.yml
  .github/workflows/packages.yaml
  README.md
  conda/recipe/meta.yaml
Labels: ci

#699 Add Transformers Torch Extras to install requirements
  README.md
  merlin_standard_lib/schema/schema.py
  requirements/base_external.txt
Labels: chore

#707 Fix the randomness in the stochastic_swap_noise tests
  tests/unit/torch/tabular/test_transformations.py
  transformers4rec/torch/utils/schema_utils.py
Labels: enhancement, area/tests

#708 adding ops-bot yaml file
  .github/ops-bot.yaml
Labels: ci
