Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-03, with the labels that each got.

#625 Make conftest pattern the same as in merlin-models
  tests/conftest.py
  tests/torch/_conftest.py
Labels: chore

#631 Adjust serving notebook to account for underlying shape changes
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
Labels: bug, P0

#626 Clean up imports in tests
  tests/torch/__init__.py
  tests/torch/_conftest.py
  tests/torch/block/test_base.py
  tests/torch/block/test_mlp.py
  tests/torch/block/test_transformer.py
  tests/torch/features/test_continuous.py
  tests/torch/features/test_embedding.py
  tests/torch/features/test_sequential.py
  tests/torch/features/test_tabular.py
  tests/torch/model/test_head.py
  tests/torch/model/test_model.py
  tests/torch/tabular/test_aggregation.py
  tests/torch/tabular/test_tabular.py
  tests/torch/tabular/test_transformations.py
  tests/torch/test_dataloader_utils.py
  tests/torch/test_experimental.py
  tests/torch/test_losses.py
  tests/torch/test_masking.py
  tests/torch/test_public_api.py
  tests/torch/test_ranking_metrics.py
  tests/torch/test_readme.py
  tests/torch/test_torchscript.py
  tests/torch/test_trainer.py
  tests/torch/utils/test_schema_utils.py
  tests/unit/test_getting_started_session_based.py
Labels: chore

#632 Migrate schema Tags to merlin.schema.Tags
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py
  merlin_standard_lib/__init__.py
  merlin_standard_lib/schema/schema.py
  merlin_standard_lib/schema/tag.py
  tests/config/test_schema.py
  tests/data/test_synthetic.py
  tests/merlin_standard_lib/schema/test_tag.py
  tests/torch/features/test_continuous.py
  tests/torch/features/test_embedding.py
  tests/torch/features/test_sequential.py
  tests/torch/features/test_tabular.py
  tests/torch/tabular/test_aggregation.py
  tests/torch/tabular/test_transformations.py
  tests/torch/utils/test_schema_utils.py
  transformers4rec/data/synthetic.py
  transformers4rec/torch/__init__.py
  transformers4rec/torch/features/embedding.py
  transformers4rec/torch/features/sequence.py
  transformers4rec/torch/features/tabular.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/utils/data_utils.py
Labels: chore

#634 Allow Schema class from core to be used to create input-blocks
  merlin_standard_lib/schema/schema.py
  tests/conftest.py
  tests/torch/features/test_tabular.py
  transformers4rec/torch/tabular/base.py
  transformers4rec/torch/utils/torch_utils.py
Labels: enhancement

#638 Allow Schema class from core to be used to create TabularSequenceFeatures
  tests/conftest.py
  tests/torch/features/test_sequential.py
  tests/torch/features/test_tabular.py
  transformers4rec/torch/features/embedding.py
Labels: enhancement

#628 Cleanup shapes in model.input_schema and output_schema
  transformers4rec/torch/model/base.py
Labels: enhancement, chore

#644 replace NVTabulardataloader with Merlindataloader
  examples/tutorial/02-ETL-with-NVTabular.ipynb
  examples/tutorial/03-Session-based-recsys.ipynb
Labels: chore, examples

#641 Fix the predictions returned by `Trainer.predict(..)`
  tests/torch/model/test_head.py
  tests/torch/model/test_model.py
  tests/torch/test_trainer.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
Labels: bug, area/pytorch

#646 fix model output_schema dims for BC/Regression task case
  transformers4rec/torch/model/base.py
Labels: area/pytorch, area/api, chore

#647 Update padding of ragged features to enable dataloader change
  tests/utils/test_padding.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/torch/utils/padding.py
  transformers4rec/torch/utils/schema_utils.py
Labels: chore

#650 Update example notebooks to create schema object from merlin core
  examples/end-to-end-session-based/01-ETL-with-NVTabular.ipynb
  examples/end-to-end-session-based/02-End-to-end-session-based-with-Yoochoose-PyT.ipynb
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
  examples/end-to-end-session-based/schema_demo.pb
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
  examples/tutorial/02-ETL-with-NVTabular.ipynb
  examples/tutorial/03-Session-based-recsys.ipynb
  examples/tutorial/04-Inference-with-Triton.ipynb
  examples/tutorial/schema_tutorial.pb
Labels: chore, examples

#510 Cropped the table and addressed comments from previous PR
  _images/DP_DDP_perf.png
  docs/source/multi_gpu_train.md
Labels: documentation, status/needs-review

#654 Set device in dataloaders
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
  transformers4rec/torch/trainer.py
Labels: bug

#627 Update usage of `use_amp` to `use_cuda_amp` for transformers>=4.20
  requirements/base_external.txt
  transformers4rec/torch/trainer.py
Labels: chore

#657 Add unit test for serving torchscript model example notebook
  tests/integration/notebooks/test_getting_started_session_based.py
Labels: area/tests, chore

#658 fix the ci script for new unit tests setup
  ci/test_unit.sh
Labels: chore, ci

#659 Remove torch.squeeze() step from the model's forward method.
  tests/unit/torch/model/test_model.py
  transformers4rec/torch/model/base.py
Labels: bug, area/inference, area/pytorch

#656 Add workflow to check if base branch of pull request is development
  .github/workflows/base-branch-check.yml
Labels: ci
