Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-01, with the labels that each got.

#586 Small fixes in getting-started ETL and training notebooks and fix tuple error in serving notebook
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
  requirements/test.txt
  tests/conftest.py
  tests/unit/test_getting_started_session_based.py
  tests/unit/test_notebooks.py
Labels: P0, area/tests, chore

#591 Fix multi-gpu documentation
  docs/source/multi_gpu_train.md
  transformers4rec/torch/utils/data_utils.py
Labels: documentation

#595 fix assert error in the test_soft_embedding unit test
  tests/torch/features/test_embedding.py
Labels: area/pytorch, area/tests, chore

#593 Update README link - End-to-end pipeline with NVIDIA Merlin
  README.md
Labels: documentation

#590 Add docstrings and the parameter to `row_groups_per_part ` to the MerlinDataLoader class
  transformers4rec/torch/utils/data_utils.py
Labels: enhancement, Multi-GPU

#537 Add Jenkinsfile
  ci/pr.gpu.Jenkinsfile
Labels: enhancement, ci, gpuCI-test-this

#600 add BC task script in readme
  README.md
  examples/getting-started-session-based/schema.pb
  transformers4rec/torch/model/prediction_task.py
Labels: documentation

#602 Update doc support instructions in README
  docs/README.md
Labels: chore, skip-changelog
