Repository NVIDIA-Merlin/Transformers4Rec, pull requests merged in 2023-04, with the labels that each got.

#665 Switch to using 2 GPU action runners for multi-GPU testing
  .github/workflows/gpu-ci.yml
Labels: chore, ci

#666 Add support for ragged inputs to model
  tests/unit/torch/model/test_model.py
  tests/unit/utils/test_padding.py
  transformers4rec/data/dataset.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/utils/data_utils.py
  transformers4rec/torch/utils/padding.py
  transformers4rec/torch/utils/schema_utils.py
Labels: enhancement

#670 extend getting started serving example to serve NVT and TF4Rec model together
  examples/getting-started-session-based/01-ETL-with-NVTabular.ipynb
  examples/getting-started-session-based/02-session-based-XLNet-with-PyT.ipynb
  examples/getting-started-session-based/03-serving-session-based-model-torch-backend.ipynb
  tests/integration/notebooks/test_getting_started_session_based.py
Labels: examples

#673 add concurrency setting to stop tests when new commits get pushed to a PR
  .github/workflows/ci.yml
  .github/workflows/docs-preview-pr.yaml
  .github/workflows/gpu-ci.yml
  .github/workflows/lint.yml
Labels: chore, ci

#663 Fix bug in get_output_sizes_from_schema with core-schema
  tests/unit/torch/utils/test_torch_utils.py
  transformers4rec/torch/utils/torch_utils.py
Labels: bug

#671 Implemented sampled softmax for NextItemPredictionTask
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_args.py
  examples/t4rec_paper_experiments/t4r_paper_repro/transf_exp_main.py
  tests/unit/torch/_conftest.py
  tests/unit/torch/model/test_model.py
  tests/unit/torch/test_losses.py
  tests/unit/torch/test_torchscript.py
  transformers4rec/torch/block/base.py
  transformers4rec/torch/losses.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/ranking_metric.py
  transformers4rec/torch/utils/torch_utils.py
Labels: enhancement

#675 Update multi-gpu notebook to set cupy device
  examples/end-to-end-session-based/03-Session-based-Yoochoose-multigpu-training-PyT.ipynb
Labels: bug, area/examples, chore

#686 Use `torch.testing.assert_close` to check model outputs
  tests/unit/torch/model/test_model.py
Labels: chore

#689 Fixing the projection layer when using weight tying and dim from Transformer output and item embedding differs
  transformers4rec/torch/model/prediction_task.py
Labels: bug

#678 Add topk arg to return topk items and scores at inference step
  tests/integration/notebooks/test_getting_started_session_based.py
  tests/unit/torch/test_torchscript_with_topk.py
  transformers4rec/torch/model/base.py
  transformers4rec/torch/model/prediction_task.py
  transformers4rec/torch/trainer.py
Labels: area/inference, chore
